# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: pages-themes/architect@v0.2.0  # https://github.com/pages-themes/architect/tree/master
plugins:
- jekyll-remote-theme

